function [tf, tffreqs, tftimes, wavelet, freqresol, timeresol] = runtf(eeg, cfg, chan)

data = squeeze(eeg.data(chan,:,:));  
 
[tf, tffreqs, tftimes, ~] = ...
    timefreq(data, eeg.srate, ...
    'cycles',       cfg.tf_cycles, ...
    'tlimits',      [eeg.xmin eeg.xmax], ...
    'wletmethod',   'dftfilt3', ...
    'ntimesout',    cfg.tf_ntimesout,...
    'freqs',        cfg.tf_freqsout, ...
    'nfreqs',       cfg.tf_nfreqs, ...
    'freqscale',    cfg.tf_freqscale, ...
    'causal',       cfg.tf_causal, ...
    'verbose',      cfg.tf_verbose);

[wavelet, cycles, freqresol, timeresol] = ...
     dftfilt3( tffreqs, cfg.tf_cycles, eeg.srate, 'cycleinc', cfg.tf_freqscale);
